services:
  - type: web
    name: payment-gateway-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input && ls -la /tmp/
    startCommand: python manage.py migrate && gunicorn payment_api.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: payment_api.settings
      - key: DEBUG
        value: False
      - key: RENDER
        value: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYSTACK_BASE_URL
        value: https://api.paystack.co
      - key: PAYSTACK_INITIALIZE_URL
        value: https://api.paystack.co/transaction/initialize
      - key: PAYSTACK_VERIFY_URL
        value: https://api.paystack.co/transaction/verify
      - key: PAYSTACK_CHARGE_URL
        value: https://api.paystack.co/transaction/charge_authorization
      - key: BASE_URL
        value: https://internpulse-paymentapi.onrender.com
    healthCheckPath: /api/v1/payments/
    autoDeploy: true
